server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(172.16.151.61:3306)/fn_sigma?charset=utf8mb4&parseTime=true&loc=Local
  redis:
    addr: 172.16.151.36:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
