// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type AlbumHTTPServer interface {
	GetAlbum(context.Context, *GetAlbumRequest) (*GetAlbumReply, error)
}

func RegisterAlbumHTTPServer(s *http.Server, srv AlbumHTTPServer) {
	r := s.Route("/")
	r.GET("/album/{id}", _Album_GetAlbum0_HTTP_Handler(srv))
}

func _Album_GetAlbum0_HTTP_Handler(srv AlbumHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAlbumRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.sigma.v1.Album/GetAlbum")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAlbum(ctx, req.(*GetAlbumRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAlbumReply)
		return ctx.Result(200, reply)
	}
}

type AlbumHTTPClient interface {
	GetAlbum(ctx context.Context, req *GetAlbumRequest, opts ...http.CallOption) (rsp *GetAlbumReply, err error)
}

type AlbumHTTPClientImpl struct {
	cc *http.Client
}

func NewAlbumHTTPClient(client *http.Client) AlbumHTTPClient {
	return &AlbumHTTPClientImpl{client}
}

func (c *AlbumHTTPClientImpl) GetAlbum(ctx context.Context, in *GetAlbumRequest, opts ...http.CallOption) (*GetAlbumReply, error) {
	var out GetAlbumReply
	pattern := "/album/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.sigma.v1.Album/GetAlbum"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
