// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/sigma/v1/wechat_user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWechatUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatBody *CreateWechatUserRequest_CreatBody `protobuf:"bytes,1,opt,name=creat_body,json=creatBody,proto3" json:"creat_body,omitempty"`
}

func (x *CreateWechatUserRequest) Reset() {
	*x = CreateWechatUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWechatUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWechatUserRequest) ProtoMessage() {}

func (x *CreateWechatUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWechatUserRequest.ProtoReflect.Descriptor instead.
func (*CreateWechatUserRequest) Descriptor() ([]byte, []int) {
	return file_api_sigma_v1_wechat_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWechatUserRequest) GetCreatBody() *CreateWechatUserRequest_CreatBody {
	if x != nil {
		return x.CreatBody
	}
	return nil
}

type CreateWechatUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateWechatUserReply) Reset() {
	*x = CreateWechatUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWechatUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWechatUserReply) ProtoMessage() {}

func (x *CreateWechatUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWechatUserReply.ProtoReflect.Descriptor instead.
func (*CreateWechatUserReply) Descriptor() ([]byte, []int) {
	return file_api_sigma_v1_wechat_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWechatUserReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateWechatUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateWechatUserReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetWechatUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWechatUserRequest) Reset() {
	*x = GetWechatUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWechatUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatUserRequest) ProtoMessage() {}

func (x *GetWechatUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatUserRequest.ProtoReflect.Descriptor instead.
func (*GetWechatUserRequest) Descriptor() ([]byte, []int) {
	return file_api_sigma_v1_wechat_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetWechatUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWechatUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetWechatUserReply) Reset() {
	*x = GetWechatUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWechatUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatUserReply) ProtoMessage() {}

func (x *GetWechatUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatUserReply.ProtoReflect.Descriptor instead.
func (*GetWechatUserReply) Descriptor() ([]byte, []int) {
	return file_api_sigma_v1_wechat_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetWechatUserReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWechatUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetWechatUserReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ListWechatUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWechatUserRequest) Reset() {
	*x = ListWechatUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWechatUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWechatUserRequest) ProtoMessage() {}

func (x *ListWechatUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWechatUserRequest.ProtoReflect.Descriptor instead.
func (*ListWechatUserRequest) Descriptor() ([]byte, []int) {
	return file_api_sigma_v1_wechat_user_proto_rawDescGZIP(), []int{4}
}

type ListWechatUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ListWechatUserReply) Reset() {
	*x = ListWechatUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWechatUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWechatUserReply) ProtoMessage() {}

func (x *ListWechatUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWechatUserReply.ProtoReflect.Descriptor instead.
func (*ListWechatUserReply) Descriptor() ([]byte, []int) {
	return file_api_sigma_v1_wechat_user_proto_rawDescGZIP(), []int{5}
}

func (x *ListWechatUserReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListWechatUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListWechatUserReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CreateWechatUserRequest_CreatBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openid   string `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Unionid  string `protobuf:"bytes,3,opt,name=unionid,proto3" json:"unionid,omitempty"`
	Appid    string `protobuf:"bytes,4,opt,name=appid,proto3" json:"appid,omitempty"`
}

func (x *CreateWechatUserRequest_CreatBody) Reset() {
	*x = CreateWechatUserRequest_CreatBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWechatUserRequest_CreatBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWechatUserRequest_CreatBody) ProtoMessage() {}

func (x *CreateWechatUserRequest_CreatBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_sigma_v1_wechat_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWechatUserRequest_CreatBody.ProtoReflect.Descriptor instead.
func (*CreateWechatUserRequest_CreatBody) Descriptor() ([]byte, []int) {
	return file_api_sigma_v1_wechat_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateWechatUserRequest_CreatBody) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *CreateWechatUserRequest_CreatBody) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateWechatUserRequest_CreatBody) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *CreateWechatUserRequest_CreatBody) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

var File_api_sigma_v1_wechat_user_proto protoreflect.FileDescriptor

var file_api_sigma_v1_wechat_user_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x77,
	0x65, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xda, 0x01, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x6f, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x57, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xe7, 0x02, 0x0a, 0x0a, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x7d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x09, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x3a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0x6d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x69, 0x67, 0x6d,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65, 0x63, 0x68,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x6b, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x69, 0x67, 0x6d,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65, 0x63, 0x68, 0x61, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x65,
	0x63, 0x68, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x42, 0x2e, 0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x1c, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sigma_v1_wechat_user_proto_rawDescOnce sync.Once
	file_api_sigma_v1_wechat_user_proto_rawDescData = file_api_sigma_v1_wechat_user_proto_rawDesc
)

func file_api_sigma_v1_wechat_user_proto_rawDescGZIP() []byte {
	file_api_sigma_v1_wechat_user_proto_rawDescOnce.Do(func() {
		file_api_sigma_v1_wechat_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sigma_v1_wechat_user_proto_rawDescData)
	})
	return file_api_sigma_v1_wechat_user_proto_rawDescData
}

var file_api_sigma_v1_wechat_user_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_sigma_v1_wechat_user_proto_goTypes = []interface{}{
	(*CreateWechatUserRequest)(nil),           // 0: api.sigma.v1.CreateWechatUserRequest
	(*CreateWechatUserReply)(nil),             // 1: api.sigma.v1.CreateWechatUserReply
	(*GetWechatUserRequest)(nil),              // 2: api.sigma.v1.GetWechatUserRequest
	(*GetWechatUserReply)(nil),                // 3: api.sigma.v1.GetWechatUserReply
	(*ListWechatUserRequest)(nil),             // 4: api.sigma.v1.ListWechatUserRequest
	(*ListWechatUserReply)(nil),               // 5: api.sigma.v1.ListWechatUserReply
	(*CreateWechatUserRequest_CreatBody)(nil), // 6: api.sigma.v1.CreateWechatUserRequest.CreatBody
}
var file_api_sigma_v1_wechat_user_proto_depIdxs = []int32{
	6, // 0: api.sigma.v1.CreateWechatUserRequest.creat_body:type_name -> api.sigma.v1.CreateWechatUserRequest.CreatBody
	0, // 1: api.sigma.v1.WechatUser.CreateWechatUser:input_type -> api.sigma.v1.CreateWechatUserRequest
	2, // 2: api.sigma.v1.WechatUser.GetWechatUser:input_type -> api.sigma.v1.GetWechatUserRequest
	4, // 3: api.sigma.v1.WechatUser.ListWechatUser:input_type -> api.sigma.v1.ListWechatUserRequest
	1, // 4: api.sigma.v1.WechatUser.CreateWechatUser:output_type -> api.sigma.v1.CreateWechatUserReply
	3, // 5: api.sigma.v1.WechatUser.GetWechatUser:output_type -> api.sigma.v1.GetWechatUserReply
	5, // 6: api.sigma.v1.WechatUser.ListWechatUser:output_type -> api.sigma.v1.ListWechatUserReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_sigma_v1_wechat_user_proto_init() }
func file_api_sigma_v1_wechat_user_proto_init() {
	if File_api_sigma_v1_wechat_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sigma_v1_wechat_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWechatUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sigma_v1_wechat_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWechatUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sigma_v1_wechat_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWechatUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sigma_v1_wechat_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWechatUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sigma_v1_wechat_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWechatUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sigma_v1_wechat_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWechatUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sigma_v1_wechat_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWechatUserRequest_CreatBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sigma_v1_wechat_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sigma_v1_wechat_user_proto_goTypes,
		DependencyIndexes: file_api_sigma_v1_wechat_user_proto_depIdxs,
		MessageInfos:      file_api_sigma_v1_wechat_user_proto_msgTypes,
	}.Build()
	File_api_sigma_v1_wechat_user_proto = out.File
	file_api_sigma_v1_wechat_user_proto_rawDesc = nil
	file_api_sigma_v1_wechat_user_proto_goTypes = nil
	file_api_sigma_v1_wechat_user_proto_depIdxs = nil
}
