// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos_study/internal/biz"
	"kratos_study/internal/conf"
	"kratos_study/internal/data"
	"kratos_study/internal/server"
	"kratos_study/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDatabase(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	wechatUserRepo := data.NewWechatUserRepo(dataData, logger)
	wechatUserUsecase := biz.NewWechatUserUsecase(wechatUserRepo, logger)
	wechatUserService := service.NewWechatUserService(wechatUserUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, wechatUserService, logger)
	grpcServer := server.NewGRPCServer(confServer, wechatUserService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
